package com.careerdungeon.domain.judgment.repository;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.core.io.ClassPathResource;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

import javax.sql.DataSource;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/** V1/V7/V8/V24의 레거시 초기화와 채점 점수 범위·세션별 멱등 DB 제약을 검증한다. */
@JdbcTest(properties = "spring.flyway.enabled=false")
class JudgmentSchemaMigrationTest {

    private static final Path MIGRATION_DIR = Path.of("src/main/resources/db/migration");

    @Autowired
    JdbcTemplate jdbcTemplate;

    @Autowired
    DataSource dataSource;

    @BeforeEach
    void setUp() {
        dropTestTables();
        jdbcTemplate.execute("""
                CREATE TABLE badges (
                    id BIGINT PRIMARY KEY,
                    stage INT NOT NULL UNIQUE
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE user_unlock_status (
                    user_id BIGINT PRIMARY KEY,
                    unlocked_level INT NOT NULL,
                    progress_gauge INT NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE interview_sessions (
                    id BIGINT PRIMARY KEY,
                    user_id BIGINT NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE answer_scores (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    session_id BIGINT NOT NULL,
                    turn INT NOT NULL,
                    score INT NOT NULL,
                    is_follow_up BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                ALTER TABLE answer_scores
                    ADD CONSTRAINT FK_interview_sessions_TO_answer_scores_1
                    FOREIGN KEY (session_id) REFERENCES interview_sessions (id) ON DELETE CASCADE
                """);
        jdbcTemplate.execute("""
                CREATE TABLE judgment_results (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    session_id BIGINT NOT NULL UNIQUE,
                    total_score INT NOT NULL,
                    passed BOOLEAN NOT NULL,
                    overall_feedback TEXT NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                ALTER TABLE judgment_results
                    ADD CONSTRAINT FK_interview_sessions_TO_judgment_results_1
                    FOREIGN KEY (session_id) REFERENCES interview_sessions (id) ON DELETE CASCADE
                """);
        jdbcTemplate.execute("""
                CREATE TABLE user_badges (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    badge_id BIGINT NOT NULL,
                    CONSTRAINT FK_badges_TO_user_badges_1
                        FOREIGN KEY (badge_id) REFERENCES badges (id)
                )
                """);
        new ResourceDatabasePopulator(
                new ClassPathResource("db/migration/V7__add_judgment_persistence_constraints.sql"),
                new ClassPathResource("db/migration/V8__add_judgment_passed_consistency.sql"))
                .execute(dataSource);
    }

    /** 공유되는 JdbcTest 컨텍스트에 FK와 최소 테이블을 남기지 않도록 정리한다. */
    @AfterEach
    void tearDown() {
        dropTestTables();
    }

    @Test
    @DisplayName("V24는 기존 3+1문항 면접과 파생 진행 상태를 새 계약 적용 전에 초기화한다")
    void legacyInterviewDataIsResetBeforeApplyingNewConstraints() {
        insertBadge(1L, 1);
        insertBadge(2L, 2);
        insertBadge(3L, 3);
        insertUnlockStatus(10L, 3, 60);
        insertUnlockStatus(20L, 2, 30);
        insertSession(1L, 10L);
        insertUserBadge(10L, 1L);
        insertUserBadge(10L, 2L);
        insertUserBadge(10L, 3L);
        insertUserBadge(20L, 2L);
        insertAnswerScore(1L, 1, 25, false);
        insertAnswerScore(1L, 2, 25, false);
        insertAnswerScore(1L, 3, 25, false);
        insertAnswerScore(1L, 4, 25, true);
        insertJudgmentResult(1L, 100, true);

        applyV24();

        assertThat(countRows("interview_sessions")).isZero();
        assertThat(countRows("answer_scores")).isZero();
        assertThat(countRows("judgment_results")).isZero();
        assertThat(jdbcTemplate.queryForObject(
                "SELECT unlocked_level FROM user_unlock_status WHERE user_id = 10",
                Integer.class)).isEqualTo(1);
        assertThat(jdbcTemplate.queryForObject(
                "SELECT progress_gauge FROM user_unlock_status WHERE user_id = 10",
                Integer.class)).isZero();
        assertThat(jdbcTemplate.queryForList(
                "SELECT badge_id FROM user_badges WHERE user_id = 10 ORDER BY badge_id",
                Long.class)).containsExactly(1L);
        assertThat(jdbcTemplate.queryForObject(
                "SELECT unlocked_level FROM user_unlock_status WHERE user_id = 20",
                Integer.class)).isEqualTo(2);
        assertThat(jdbcTemplate.queryForObject(
                "SELECT progress_gauge FROM user_unlock_status WHERE user_id = 20",
                Integer.class)).isEqualTo(30);
        assertThat(jdbcTemplate.queryForList(
                "SELECT badge_id FROM user_badges WHERE user_id = 20",
                Long.class)).containsExactly(2L);
    }

    @Test
    @DisplayName("answer_scores는 세션과 turn 조합의 중복을 DB에서 거부한다")
    void duplicateSessionTurnIsRejected() {
        applyV24();
        insertSession(1L, 10L);
        insertAnswerScore(1L, 1, 20, false);

        assertThatThrownBy(() -> insertAnswerScore(1L, 1, 20, false))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    @DisplayName("answer_scores는 turn·score·꼬리질문 플래그 불변식을 DB에서 강제한다")
    void invalidAnswerScoreRangeAndFollowUpFlagAreRejected() {
        applyV24();
        insertSession(1L, 10L);

        assertThatThrownBy(() -> insertAnswerScore(1L, 1, 21, false))
                .isInstanceOf(DataIntegrityViolationException.class);
        assertThatThrownBy(() -> insertAnswerScore(1L, 5, 20, false))
                .isInstanceOf(DataIntegrityViolationException.class);
        assertThatThrownBy(() -> insertAnswerScore(1L, 4, 20, true))
                .isInstanceOf(DataIntegrityViolationException.class);

        insertAnswerScore(1L, 5, 20, true);
    }

    @Test
    @DisplayName("judgment_results는 총점 범위와 세션당 단일 판정을 DB에서 강제한다")
    void judgmentResultRangeAndSessionUniquenessAreEnforced() {
        applyV24();
        insertSession(1L, 10L);
        insertSession(2L, 10L);
        insertJudgmentResult(1L, 80, true);

        assertThatThrownBy(() -> insertJudgmentResult(1L, 81, true))
                .isInstanceOf(DataIntegrityViolationException.class);
        assertThatThrownBy(() -> insertJudgmentResult(2L, 101, true))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    @DisplayName("judgment_results의 passed는 레벨별 기준을 위해 애플리케이션에서 검증한다")
    void judgmentPassedAllowsLevelSpecificApplicationValidation() {
        applyV24();
        insertSession(1L, 10L);
        insertSession(2L, 10L);
        insertJudgmentResult(1L, 60, true);
        insertJudgmentResult(2L, 60, false);

        assertThat(jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM judgment_results",
                Integer.class)).isEqualTo(2);
    }

    @Test
    @DisplayName("V1은 JudgmentResult sessionId UNIQUE 제약을 명시한다")
    void v1DeclaresJudgmentSessionUniqueConstraint() throws IOException {
        String v1 = Files.readString(MIGRATION_DIR.resolve("V1__init.sql"));

        assertThat(v1).contains("UK_judgment_results_session_id");
        assertThat(v1).contains("`session_id`");
    }

    /** 검증 대상인 V24 마이그레이션을 현재 테스트 스키마에 적용한다. */
    private void applyV24() {
        new ResourceDatabasePopulator(
                new ClassPathResource("db/migration/V24__rebalance_judgment_scoring_constraints.sql"))
                .execute(dataSource);
    }

    /** 테스트용 면접 세션을 저장한다. */
    private void insertSession(long sessionId, long userId) {
        jdbcTemplate.update(
                "INSERT INTO interview_sessions (id, user_id) VALUES (?, ?)",
                sessionId,
                userId);
    }

    /** 테스트용 해금·진행도 상태를 저장한다. */
    private void insertUnlockStatus(long userId, int unlockedLevel, int progressGauge) {
        jdbcTemplate.update("""
                        INSERT INTO user_unlock_status (user_id, unlocked_level, progress_gauge)
                        VALUES (?, ?, ?)
                        """,
                userId,
                unlockedLevel,
                progressGauge);
    }

    /** 테스트용 뱃지 기준 데이터를 저장한다. */
    private void insertBadge(long badgeId, int stage) {
        jdbcTemplate.update(
                "INSERT INTO badges (id, stage) VALUES (?, ?)",
                badgeId,
                stage);
    }

    /** 테스트용 사용자 획득 뱃지를 저장한다. */
    private void insertUserBadge(long userId, long badgeId) {
        jdbcTemplate.update(
                "INSERT INTO user_badges (user_id, badge_id) VALUES (?, ?)",
                userId,
                badgeId);
    }

    /** 테스트용 문항 점수를 저장한다. */
    private void insertAnswerScore(long sessionId, int turn, int score, boolean followUp) {
        jdbcTemplate.update("""
                        INSERT INTO answer_scores (session_id, turn, score, is_follow_up, feedback)
                        VALUES (?, ?, ?, ?, ?)
                        """,
                sessionId, turn, score, followUp, "피드백");
    }

    /** 테스트용 최종 판정 결과를 저장한다. */
    private void insertJudgmentResult(long sessionId, int totalScore, boolean passed) {
        jdbcTemplate.update("""
                        INSERT INTO judgment_results (session_id, total_score, passed, overall_feedback)
                        VALUES (?, ?, ?, ?)
                        """,
                sessionId, totalScore, passed, "종합 피드백");
    }

    /** 지정한 테스트 테이블의 전체 행 수를 반환한다. */
    private int countRows(String tableName) {
        return jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM " + tableName,
                Integer.class);
    }

    /** FK 의존 순서에 맞춰 이 테스트가 만든 최소 스키마를 제거한다. */
    private void dropTestTables() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS user_badges");
        jdbcTemplate.execute("DROP TABLE IF EXISTS judgment_results");
        jdbcTemplate.execute("DROP TABLE IF EXISTS answer_scores");
        jdbcTemplate.execute("DROP TABLE IF EXISTS interview_sessions");
        jdbcTemplate.execute("DROP TABLE IF EXISTS user_unlock_status");
        jdbcTemplate.execute("DROP TABLE IF EXISTS badges");
    }
}
