package com.careerdungeon.domain.judgment.repository;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.core.io.ClassPathResource;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

import javax.sql.DataSource;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/** V1/V7/V8/V24의 채점 점수 범위와 세션별 멱등 DB 제약을 검증한다. */
@JdbcTest(properties = "spring.flyway.enabled=false")
class JudgmentSchemaMigrationTest {

    private static final Path MIGRATION_DIR = Path.of("src/main/resources/db/migration");

    @Autowired
    JdbcTemplate jdbcTemplate;

    @Autowired
    DataSource dataSource;

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS judgment_results");
        jdbcTemplate.execute("DROP TABLE IF EXISTS answer_scores");
        jdbcTemplate.execute("""
                CREATE TABLE answer_scores (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    session_id BIGINT NOT NULL,
                    turn INT NOT NULL,
                    score INT NOT NULL,
                    is_follow_up BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE judgment_results (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    session_id BIGINT NOT NULL UNIQUE,
                    total_score INT NOT NULL,
                    passed BOOLEAN NOT NULL,
                    overall_feedback TEXT NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        new ResourceDatabasePopulator(
                new ClassPathResource("db/migration/V7__add_judgment_persistence_constraints.sql"),
                new ClassPathResource("db/migration/V8__add_judgment_passed_consistency.sql"),
                new ClassPathResource("db/migration/V24__rebalance_judgment_scoring_constraints.sql"))
                .execute(dataSource);
    }

    @Test
    @DisplayName("answer_scores는 세션과 turn 조합의 중복을 DB에서 거부한다")
    void duplicateSessionTurnIsRejected() {
        insertAnswerScore(1L, 1, 20, false);

        assertThatThrownBy(() -> insertAnswerScore(1L, 1, 20, false))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    @DisplayName("answer_scores는 turn·score·꼬리질문 플래그 불변식을 DB에서 강제한다")
    void invalidAnswerScoreRangeAndFollowUpFlagAreRejected() {
        assertThatThrownBy(() -> insertAnswerScore(1L, 1, 21, false))
                .isInstanceOf(DataIntegrityViolationException.class);
        assertThatThrownBy(() -> insertAnswerScore(1L, 5, 20, false))
                .isInstanceOf(DataIntegrityViolationException.class);
        assertThatThrownBy(() -> insertAnswerScore(1L, 4, 20, true))
                .isInstanceOf(DataIntegrityViolationException.class);

        insertAnswerScore(1L, 5, 20, true);
    }

    @Test
    @DisplayName("judgment_results는 총점 범위와 세션당 단일 판정을 DB에서 강제한다")
    void judgmentResultRangeAndSessionUniquenessAreEnforced() {
        insertJudgmentResult(1L, 80, true);

        assertThatThrownBy(() -> insertJudgmentResult(1L, 81, true))
                .isInstanceOf(DataIntegrityViolationException.class);
        assertThatThrownBy(() -> insertJudgmentResult(2L, 101, true))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    @DisplayName("judgment_results의 passed는 레벨별 기준을 위해 애플리케이션에서 검증한다")
    void judgmentPassedAllowsLevelSpecificApplicationValidation() {
        insertJudgmentResult(1L, 60, true);
        insertJudgmentResult(2L, 60, false);

        assertThat(jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM judgment_results",
                Integer.class)).isEqualTo(2);
    }

    @Test
    @DisplayName("V1은 JudgmentResult sessionId UNIQUE 제약을 명시한다")
    void v1DeclaresJudgmentSessionUniqueConstraint() throws IOException {
        String v1 = Files.readString(MIGRATION_DIR.resolve("V1__init.sql"));

        assertThat(v1).contains("UK_judgment_results_session_id");
        assertThat(v1).contains("`session_id`");
    }

    private void insertAnswerScore(long sessionId, int turn, int score, boolean followUp) {
        jdbcTemplate.update("""
                        INSERT INTO answer_scores (session_id, turn, score, is_follow_up, feedback)
                        VALUES (?, ?, ?, ?, ?)
                        """,
                sessionId, turn, score, followUp, "피드백");
    }

    private void insertJudgmentResult(long sessionId, int totalScore, boolean passed) {
        jdbcTemplate.update("""
                        INSERT INTO judgment_results (session_id, total_score, passed, overall_feedback)
                        VALUES (?, ?, ?, ?)
                        """,
                sessionId, totalScore, passed, "종합 피드백");
    }
}
