package com.careerdungeon.domain.progress.repository;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

import javax.sql.DataSource;

import static org.assertj.core.api.Assertions.assertThat;

/** V10 뱃지 seed가 신규·기존 환경을 같은 기준 데이터로 수렴시키는지 검증한다. */
@JdbcTest(properties = "spring.flyway.enabled=false")
class BadgeSeedMigrationTest {

    @Autowired
    JdbcTemplate jdbcTemplate;

    @Autowired
    DataSource dataSource;

    /** 실제 운영 컬럼과 Stage UNIQUE 제약을 가진 최소 badges 테이블을 준비한다. */
    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS badges");
        jdbcTemplate.execute("""
                CREATE TABLE badges (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    stage INT NOT NULL UNIQUE,
                    name VARCHAR(100) NOT NULL,
                    image_url VARCHAR(255) NOT NULL,
                    unlock_condition VARCHAR(50) NOT NULL
                )
                """);
    }

    /** 빈 DB에 Stage1~4 기준 데이터와 확정 표시 계약이 생성되는지 검증한다. */
    @Test
    @DisplayName("빈 DB에 Stage1~4 뱃지 기준 데이터를 생성한다")
    void seedsAllBadgeStages() {
        runMigration();

        assertThat(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM badges", Integer.class)).isEqualTo(4);
        assertThat(jdbcTemplate.queryForMap("SELECT * FROM badges WHERE stage = 1"))
                .containsEntry("name", "프로그래머쓱 LEVEL 1")
                .containsEntry("image_url", "/badges/Level1.png")
                .containsEntry("unlock_condition", "SIGNUP");
        assertThat(jdbcTemplate.queryForMap("SELECT * FROM badges WHERE stage = 4"))
                .containsEntry("name", "프로그래머쓱 LEVEL 4")
                .containsEntry("image_url", "/badges/Level4.png")
                .containsEntry("unlock_condition", "LEVEL3_UNLOCK");
    }

    /** 수동 데이터가 있거나 스크립트를 재실행해도 Stage별 한 건과 확정값을 유지하는지 검증한다. */
    @Test
    @DisplayName("기존 Stage 데이터는 확정값으로 동기화하고 중복 생성하지 않는다")
    void synchronizesExistingStageWithoutDuplicates() {
        jdbcTemplate.update("""
                INSERT INTO badges (stage, name, image_url, unlock_condition)
                VALUES (1, '임시 이름', '/old.png', 'SIGNUP')
                """);

        runMigration();
        runMigration();

        assertThat(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM badges", Integer.class)).isEqualTo(4);
        assertThat(jdbcTemplate.queryForObject(
                "SELECT name FROM badges WHERE stage = 1", String.class))
                .isEqualTo("프로그래머쓱 LEVEL 1");
    }

    /** 클래스패스의 실제 Flyway seed 파일을 테스트 DB에 적용한다. */
    private void runMigration() {
        new ResourceDatabasePopulator(
                new ClassPathResource("db/migration/V10__seed_badges.sql"))
                .execute(dataSource);
    }
}
