package com.careerdungeon.domain.progress.repository;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

import javax.sql.DataSource;

import static org.assertj.core.api.Assertions.assertThat;

/** V16이 기존 정적 이미지 URL을 private S3 object key로 안전하게 전환하는지 검증한다. */
@JdbcTest(properties = "spring.flyway.enabled=false")
class BadgeS3KeyMigrationTest {

    @Autowired
    JdbcTemplate jdbcTemplate;

    @Autowired
    DataSource dataSource;

    /** V10과 동일한 컬럼 구조를 가진 최소 badges 테이블을 준비한다. */
    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS badges");
        jdbcTemplate.execute("""
                CREATE TABLE badges (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    stage INT NOT NULL UNIQUE,
                    name VARCHAR(100) NOT NULL,
                    image_url VARCHAR(255) NOT NULL,
                    unlock_condition VARCHAR(50) NOT NULL
                )
                """);
    }

    /** 네 Stage를 동일한 badges 접두사의 S3 키로 바꾸는지 검증한다. */
    @Test
    @DisplayName("Stage1~4 이미지 기준 데이터를 S3 object key로 전환한다")
    void migratesStaticPathsToS3ObjectKeys() {
        runMigration("db/migration/V10__seed_badges.sql");
        runMigration("db/migration/V16__move_badge_images_to_s3_keys.sql");

        assertThat(jdbcTemplate.queryForList(
                "SELECT image_url FROM badges ORDER BY stage", String.class))
                .containsExactly(
                        "badges/Level1.png",
                        "badges/Level2.png",
                        "badges/Level3.png",
                        "badges/Level4.png");
    }

    /** 클래스패스의 실제 Flyway 파일을 테스트 DB에 적용한다. */
    private void runMigration(String classpath) {
        new ResourceDatabasePopulator(new ClassPathResource(classpath)).execute(dataSource);
    }
}
