package com.careerdungeon.domain.progress.repository;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

import javax.sql.DataSource;

import static org.assertj.core.api.Assertions.assertThat;

/** V22가 뱃지 기능 도입 전에 가입한 사용자의 초기 진행도와 Stage1 뱃지를 보정하는지 검증한다. */
@JdbcTest(properties = "spring.flyway.enabled=false")
class SignupProgressBackfillMigrationTest {

    @Autowired
    JdbcTemplate jdbcTemplate;

    @Autowired
    DataSource dataSource;

    /** 운영 마이그레이션에 필요한 최소 테이블과 기존 사용자 데이터를 준비한다. */
    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS user_badges");
        jdbcTemplate.execute("DROP TABLE IF EXISTS user_unlock_status");
        jdbcTemplate.execute("DROP TABLE IF EXISTS badges");
        jdbcTemplate.execute("DROP TABLE IF EXISTS users");
        jdbcTemplate.execute("""
                CREATE TABLE users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    google_id VARCHAR(255) NOT NULL UNIQUE,
                    email VARCHAR(255) NOT NULL,
                    name VARCHAR(100) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE user_unlock_status (
                    user_id BIGINT PRIMARY KEY,
                    unlocked_level INT NOT NULL,
                    progress_gauge INT NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE badges (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    stage INT NOT NULL UNIQUE
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE user_badges (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    badge_id BIGINT NOT NULL,
                    acquired_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE (user_id, badge_id)
                )
                """);

        jdbcTemplate.update("INSERT INTO users (google_id, email, name) VALUES (?, ?, ?)",
                "legacy-missing", "missing@example.com", "누락 사용자");
        jdbcTemplate.update("INSERT INTO users (google_id, email, name) VALUES (?, ?, ?)",
                "legacy-existing", "existing@example.com", "기존 사용자");
        jdbcTemplate.update("INSERT INTO badges (stage) VALUES (1)");
        jdbcTemplate.update("INSERT INTO badges (stage) VALUES (2)");
        jdbcTemplate.update("""
                INSERT INTO user_unlock_status (user_id, unlocked_level, progress_gauge)
                SELECT id, 2, 30 FROM users WHERE google_id = 'legacy-existing'
                """);
        jdbcTemplate.update("""
                INSERT INTO user_badges (user_id, badge_id)
                SELECT users.id, badges.id
                FROM users JOIN badges ON badges.stage = 1
                WHERE users.google_id = 'legacy-existing'
                """);
    }

    /** 누락 사용자만 초기 상태와 Stage1 뱃지를 얻고 기존 진행도는 보존되는지 검증한다. */
    @Test
    @DisplayName("기존 가입자의 누락된 초기 진행도와 Stage1 뱃지를 멱등하게 보정한다")
    void backfillsMissingSignupProgressAndBadgeIdempotently() {
        runMigration();
        runMigration();

        assertThat(jdbcTemplate.queryForMap("""
                SELECT unlocked_level, progress_gauge
                FROM user_unlock_status
                WHERE user_id = (SELECT id FROM users WHERE google_id = 'legacy-missing')
                """))
                .containsEntry("UNLOCKED_LEVEL", 1)
                .containsEntry("PROGRESS_GAUGE", 0);
        assertThat(jdbcTemplate.queryForMap("""
                SELECT unlocked_level, progress_gauge
                FROM user_unlock_status
                WHERE user_id = (SELECT id FROM users WHERE google_id = 'legacy-existing')
                """))
                .containsEntry("UNLOCKED_LEVEL", 2)
                .containsEntry("PROGRESS_GAUGE", 30);
        assertThat(jdbcTemplate.queryForObject("""
                SELECT COUNT(*)
                FROM user_badges
                WHERE badge_id = (SELECT id FROM badges WHERE stage = 1)
                """, Integer.class)).isEqualTo(2);
        assertThat(jdbcTemplate.queryForObject("""
                SELECT user_badges.acquired_at = users.created_at
                FROM user_badges
                JOIN users ON users.id = user_badges.user_id
                WHERE users.google_id = 'legacy-missing'
                """, Boolean.class)).isTrue();
    }

    /** 클래스패스의 실제 Flyway 백필 파일을 테스트 DB에 적용한다. */
    private void runMigration() {
        new ResourceDatabasePopulator(
                new ClassPathResource("db/migration/V22__backfill_signup_progress_and_stage1_badges.sql"))
                .execute(dataSource);
    }
}
