package com.careerdungeon.domain.message;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.core.io.ClassPathResource;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

import javax.sql.DataSource;

import static org.assertj.core.api.Assertions.assertThatThrownBy;

@JdbcTest(properties = "spring.flyway.enabled=false")
class MessageSchemaMigrationTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private DataSource dataSource;

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS messages");
        jdbcTemplate.execute("""
                CREATE TABLE messages (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    session_id BIGINT NOT NULL,
                    role VARCHAR(20) NOT NULL,
                    content TEXT NOT NULL,
                    turn INT NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);

        new ResourceDatabasePopulator(
                new ClassPathResource("db/migration/V5__add_messages_session_role_turn_unique.sql"))
                .execute(dataSource);
    }

    @Test
    @DisplayName("duplicate session_id, role, turn violates unique constraint")
    void duplicateSessionRoleTurn_violatesUniqueConstraint() {
        insertMessage(1L, "QUESTION", 1, "first question");

        assertThatThrownBy(() -> insertMessage(1L, "QUESTION", 1, "duplicate question"))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    private void insertMessage(long sessionId, String role, int turn, String content) {
        jdbcTemplate.update("""
                        INSERT INTO messages (session_id, role, content, turn)
                        VALUES (?, ?, ?, ?)
                        """,
                sessionId, role, content, turn);
    }
}
