package com.careerdungeon.domain.auth.repository;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.jdbc.core.JdbcTemplate;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * ADR-015 / V10__cascade_delete_on_user_withdrawal.sql이 실제로 회원 탈퇴 시
 * "전체 즉시 삭제"(privacy-policy.md) 요구사항대로 users 행 삭제 하나로 전체 체인이
 * 지워지는지 검증한다. V1/V4가 이미 만들어둔 테이블을 이 클래스가 다시 만드므로,
 * `spring.flyway.enabled=false`로 같은 H2 컨텍스트를 공유하는 다른 @JdbcTest와 스키마가
 * 겹치지 않도록 매번 명시적으로 DROP 후 재생성한다(MessageSchemaMigrationTest와 동일한 이유).
 */
@JdbcTest(properties = "spring.flyway.enabled=false")
class UserWithdrawalCascadeDeleteTest {

    @Autowired
    JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS questions CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS user_badges CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS refresh_tokens CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS judgment_results CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS answer_scores CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS messages CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS interview_sessions CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS resumes CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS badges CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS user_unlock_status CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS users CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS persona_config CASCADE");

        jdbcTemplate.execute("""
                CREATE TABLE persona_config (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    level INT NOT NULL,
                    tone VARCHAR(20) NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    google_id VARCHAR(255) NOT NULL UNIQUE,
                    email VARCHAR(255) NOT NULL,
                    name VARCHAR(100) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE user_unlock_status (
                    user_id BIGINT NOT NULL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
                    unlocked_level INT NOT NULL DEFAULT 1,
                    progress_gauge INT NOT NULL DEFAULT 0
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE badges (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    stage INT NOT NULL,
                    name VARCHAR(100) NOT NULL,
                    image_url VARCHAR(255) NOT NULL,
                    unlock_condition VARCHAR(50) NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE resumes (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    type VARCHAR(20) NOT NULL DEFAULT 'RESUME',
                    s3_key VARCHAR(255) NOT NULL,
                    extracted_text TEXT NULL,
                    parse_status VARCHAR(20) NOT NULL,
                    file_hash VARCHAR(64) NOT NULL,
                    cache_expires_at TIMESTAMP NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE interview_sessions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    resume_id BIGINT NOT NULL REFERENCES resumes(id) ON DELETE CASCADE,
                    persona_config_id BIGINT NOT NULL REFERENCES persona_config(id),
                    selected_keyword VARCHAR(20) NOT NULL,
                    status VARCHAR(20) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE messages (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    session_id BIGINT NOT NULL REFERENCES interview_sessions(id) ON DELETE CASCADE,
                    role VARCHAR(20) NOT NULL,
                    content TEXT NOT NULL,
                    turn INT NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE questions (
                    message_id BIGINT NOT NULL PRIMARY KEY REFERENCES messages(id) ON DELETE CASCADE,
                    expected_answer TEXT NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE answer_scores (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    session_id BIGINT NOT NULL REFERENCES interview_sessions(id) ON DELETE CASCADE,
                    turn INT NOT NULL,
                    score INT NOT NULL,
                    is_follow_up BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE judgment_results (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    session_id BIGINT NOT NULL UNIQUE REFERENCES interview_sessions(id) ON DELETE CASCADE,
                    total_score INT NOT NULL,
                    passed BOOLEAN NOT NULL,
                    overall_feedback TEXT NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE refresh_tokens (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    token_hash VARCHAR(255) NOT NULL,
                    expires_at TIMESTAMP NOT NULL,
                    revoked BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE user_badges (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    badge_id BIGINT NOT NULL REFERENCES badges(id),
                    acquired_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
    }

    // @JdbcTest(properties = "spring.flyway.enabled=false")로 같은 설정을 쓰는 다른 테스트
    // 클래스(MessageSchemaMigrationTest 등)와 Spring이 H2 컨텍스트/데이터소스를 공유한다.
    // 여기서 만든 테이블(특히 messages FK를 가진 questions)을 남겨두면 그 테스트가 자기
    // 테이블을 DROP하다가 우리 FK에 막혀 실패하므로, 테스트가 끝나면 반드시 치운다.
    @AfterEach
    void tearDown() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS questions CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS user_badges CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS refresh_tokens CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS judgment_results CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS answer_scores CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS messages CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS interview_sessions CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS resumes CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS badges CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS user_unlock_status CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS users CASCADE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS persona_config CASCADE");
    }

    @Test
    @DisplayName("users 행을 지우면 사용자 소유 데이터 전체(이력서/세션/메시지/질문/채점/토큰/뱃지/진행도)가 함께 삭제된다")
    void deletingUser_cascadesThroughEntireOwnedDataChain() {
        long personaId = insertPersonaConfig();
        long badgeId = insertBadge();
        long userId = insertUser();
        long resumeId = insertResume(userId);
        long sessionId = insertInterviewSession(userId, resumeId, personaId);
        long messageId = insertMessage(sessionId);
        insertQuestion(messageId);
        insertAnswerScore(sessionId);
        insertJudgmentResult(sessionId);
        insertRefreshToken(userId);
        insertUserBadge(userId, badgeId);
        insertUserUnlockStatus(userId);

        jdbcTemplate.update("DELETE FROM users WHERE id = ?", userId);

        assertThat(countWhere("users", "id", userId)).isZero();
        assertThat(countWhere("resumes", "id", resumeId)).isZero();
        assertThat(countWhere("interview_sessions", "id", sessionId)).isZero();
        assertThat(countWhere("messages", "id", messageId)).isZero();
        assertThat(countWhere("questions", "message_id", messageId)).isZero();
        assertThat(countWhere("answer_scores", "session_id", sessionId)).isZero();
        assertThat(countWhere("judgment_results", "session_id", sessionId)).isZero();
        assertThat(countWhere("refresh_tokens", "user_id", userId)).isZero();
        assertThat(countWhere("user_badges", "user_id", userId)).isZero();
        assertThat(countWhere("user_unlock_status", "user_id", userId)).isZero();

        // 공유 참조 테이블(다른 유저도 같이 쓰는 마스터 데이터)은 캐스케이드 대상이 아니어야 한다.
        assertThat(countWhere("badges", "id", badgeId)).isEqualTo(1);
        assertThat(countWhere("persona_config", "id", personaId)).isEqualTo(1);
    }

    private long insertPersonaConfig() {
        jdbcTemplate.update("INSERT INTO persona_config (level, tone) VALUES (1, 'lenient')");
        return lastInsertId("persona_config");
    }

    private long insertBadge() {
        jdbcTemplate.update("""
                INSERT INTO badges (stage, name, image_url, unlock_condition)
                VALUES (1, '뱃지', 'http://example.com/badge.png', 'SIGNUP')
                """);
        return lastInsertId("badges");
    }

    private long insertUser() {
        jdbcTemplate.update("""
                INSERT INTO users (google_id, email, name) VALUES ('google-1', 'a@b.com', '홍길동')
                """);
        return lastInsertId("users");
    }

    private long insertResume(long userId) {
        jdbcTemplate.update("""
                INSERT INTO resumes (user_id, type, s3_key, parse_status, file_hash)
                VALUES (?, 'RESUME', 'some/key.pdf', 'DONE', 'hash')
                """, userId);
        return lastInsertId("resumes");
    }

    private long insertInterviewSession(long userId, long resumeId, long personaId) {
        jdbcTemplate.update("""
                INSERT INTO interview_sessions (user_id, resume_id, persona_config_id, selected_keyword, status)
                VALUES (?, ?, ?, 'DB', 'IN_PROGRESS')
                """, userId, resumeId, personaId);
        return lastInsertId("interview_sessions");
    }

    private long insertMessage(long sessionId) {
        jdbcTemplate.update("""
                INSERT INTO messages (session_id, role, content, turn) VALUES (?, 'QUESTION', '질문', 1)
                """, sessionId);
        return lastInsertId("messages");
    }

    private void insertQuestion(long messageId) {
        jdbcTemplate.update("""
                INSERT INTO questions (message_id, expected_answer) VALUES (?, '모범답안')
                """, messageId);
    }

    private void insertAnswerScore(long sessionId) {
        jdbcTemplate.update("""
                INSERT INTO answer_scores (session_id, turn, score, is_follow_up) VALUES (?, 1, 20, FALSE)
                """, sessionId);
    }

    private void insertJudgmentResult(long sessionId) {
        jdbcTemplate.update("""
                INSERT INTO judgment_results (session_id, total_score, passed, overall_feedback)
                VALUES (?, 80, TRUE, '종합 피드백')
                """, sessionId);
    }

    private void insertRefreshToken(long userId) {
        jdbcTemplate.update("""
                INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
                VALUES (?, 'tokenhash', DATEADD('DAY', 7, CURRENT_TIMESTAMP))
                """, userId);
    }

    private void insertUserBadge(long userId, long badgeId) {
        jdbcTemplate.update("INSERT INTO user_badges (user_id, badge_id) VALUES (?, ?)", userId, badgeId);
    }

    private void insertUserUnlockStatus(long userId) {
        jdbcTemplate.update("INSERT INTO user_unlock_status (user_id) VALUES (?)", userId);
    }

    private long lastInsertId(String table) {
        Long id = jdbcTemplate.queryForObject("SELECT MAX(id) FROM " + table, Long.class);
        return id;
    }

    private int countWhere(String table, String column, long value) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM " + table + " WHERE " + column + " = ?", Integer.class, value);
        return count == null ? 0 : count;
    }
}
