package com.careerdungeon.domain.persona;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

import javax.sql.DataSource;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@JdbcTest(properties = "spring.flyway.enabled=false")
class PersonaConfigSeedMigrationTest {

    @Autowired
    JdbcTemplate jdbcTemplate;

    @Autowired
    DataSource dataSource;

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS persona_config");
        jdbcTemplate.execute("""
                CREATE TABLE persona_config (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    level INT NOT NULL,
                    tone VARCHAR(20) NOT NULL
                )
                """);
    }

    @Test
    @DisplayName("빈 DB에 Lv.1/Lv.2 기본 페르소나를 생성한다")
    void seedsDefaultPersonaConfigs() {
        runSeedMigration();
        runUniqueConstraintMigration();

        assertThat(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM persona_config", Integer.class))
                .isEqualTo(2);
        assertThat(jdbcTemplate.queryForMap("SELECT * FROM persona_config WHERE level = 1"))
                .containsEntry("tone", "LENIENT");
        assertThat(jdbcTemplate.queryForMap("SELECT * FROM persona_config WHERE level = 2"))
                .containsEntry("tone", "STRICT");
    }

    @Test
    @DisplayName("기존 level 데이터가 있으면 중복 생성하지 않고 canonical tone으로 보정한다")
    void synchronizesExistingLevelsWithoutDuplicates() {
        jdbcTemplate.update("INSERT INTO persona_config (level, tone) VALUES (1, 'STRICT')");

        runSeedMigration();
        runUniqueConstraintMigration();

        assertThat(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM persona_config", Integer.class))
                .isEqualTo(2);
        assertThat(jdbcTemplate.queryForObject(
                "SELECT tone FROM persona_config WHERE level = 1", String.class))
                .isEqualTo("LENIENT");
    }

    @Test
    @DisplayName("중복 level 데이터가 있으면 UNIQUE 제약 추가 단계에서 실패한다")
    void duplicateLevelsFailWhenAddingUniqueConstraint() {
        jdbcTemplate.update("INSERT INTO persona_config (level, tone) VALUES (1, 'LENIENT')");
        jdbcTemplate.update("INSERT INTO persona_config (level, tone) VALUES (1, 'STRICT')");

        runSeedMigration();

        assertThatThrownBy(this::runUniqueConstraintMigration)
                .isInstanceOf(RuntimeException.class);
    }

    private void runSeedMigration() {
        new ResourceDatabasePopulator(
                new ClassPathResource("db/migration/V12__seed_persona_config.sql"))
                .execute(dataSource);
    }

    private void runUniqueConstraintMigration() {
        new ResourceDatabasePopulator(
                new ClassPathResource("db/migration/V13__add_persona_config_level_unique.sql"))
                .execute(dataSource);
    }
}
